# Generated by Django 4.2.3 on 2024-02-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.CharField(default="", max_length=8, unique=True)),
                ("username", models.CharField(max_length=10, unique=True)),
                ("firstname", models.CharField(max_length=254)),
                ("lastname", models.CharField(max_length=254)),
                ("email", models.EmailField(max_length=254)),
                ("is_freelancer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
