# Generated by Django 4.2.3 on 2024-02-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
