# Generated by Django 4.2.3 on 2024-02-28 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="appointmentDate",
        ),
        migrations.AddField(
            model_name="appointment",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
