# Generated by Django 4.2.3 on 2024-02-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_remove_appointment_appointmentdate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="clent",
            new_name="client",
        ),
    ]
