# Generated by Django 4.2.3 on 2024-02-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_rename_clent_appointment_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
