# Generated by Django 4.2.3 on 2024-03-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_appointment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=10,
            ),
        ),
    ]
