# Generated by Django 4.2.3 on 2024-02-27 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posting_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Freelancer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FreelancerID",
                    models.CharField(
                        default=posting_service.models.generate_unique_code,
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ServiceID",
                    models.CharField(
                        default=posting_service.models.generate_unique_code,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("serviceName", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("portfolio", models.ImageField(upload_to="")),
                ("credentials", models.FileField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posting_service.freelancer",
                    ),
                ),
            ],
        ),
    ]
