# Generated by Django 4.2.3 on 2024-02-27 10:23

from django.db import migrations, models
import posting_service.models


class Migration(migrations.Migration):

    dependencies = [
        ("posting_service", "0002_remove_service_freelancer_delete_freelancer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="credentials",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=posting_service.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="portfolio",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=posting_service.models.user_directory_path,
            ),
        ),
    ]
