# Generated by Django 4.2.3 on 2024-02-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posting_service", "0003_alter_service_credentials_alter_service_portfolio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="credentials",
        ),
        migrations.RemoveField(
            model_name="service",
            name="portfolio",
        ),
    ]
