# Generated by Django 4.2.3 on 2024-03-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting_service", "0004_remove_service_credentials_remove_service_portfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_img",
            field=models.ImageField(blank=True, null=True, upload_to="service_images/"),
        ),
    ]
