# Generated by Django 4.2.3 on 2024-03-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting_service", "0005_service_service_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
