# Generated by Django 4.2.3 on 2024-03-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting_service", "0007_service_freelancer"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="credentials",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
