# Generated by Django 4.2.3 on 2024-03-06 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posting_service", "0008_service_credentials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="service_img",
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_img",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posting_service.service",
                    ),
                ),
            ],
        ),
    ]
