# Generated by Django 4.2.3 on 2024-03-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting_service", "0009_remove_service_service_img_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDUCATION", "Education"),
                    ("PERSONAL CARE AND GROOMING", "Personal Care and Grooming"),
                    ("CLEANING AND JANITORIAL", "Cleaning and Janitorial"),
                    ("CONSTRUCTION AND RENOVATION", "Construction and Renovation"),
                    ("LANDSCAPING AND GARDENING", "Landscaping and Gardening"),
                    ("PET CARE", "Pet Care"),
                    ("TECHNOLOGY", "Technology"),
                    ("OTHER", "Other"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
