# Generated by Django 4.2.3 on 2024-03-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting_service", "0010_service_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDUCATION", "Education"),
                    ("PERSONAL CARE AND GROOMING", "Personal Care and Grooming"),
                    ("CLEANING AND JANITORIAL", "Cleaning and Janitorial"),
                    ("CONSTRUCTION AND RENOVATION", "Construction and Renovation"),
                    ("LANDSCAPING AND GARDENING", "Landscaping and Gardening"),
                    ("CHILD AND PET CARE", "Child and Pet Care"),
                    ("TECHNOLOGY AND CREATIVE ARTS", "Technology and Creative Arts"),
                    ("OTHER", "Other"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
